"""Shared constants for the chat protocol."""

APP_NAME = "Private Chat"
VERSION = "1.0.0"
PACKET_VERSION = 1
HEARTBEAT_INTERVAL_SECONDS = 15.0
PING_INTERVAL_SECONDS = 10.0
TYPING_TIMEOUT_SECONDS = 3.0
RECONNECT_INITIAL_SECONDS = 1.0
RECONNECT_MAX_SECONDS = 30.0
CHUNK_SIZE = 1024 * 1024
